### ISSUE TITLE
License URL is broken

### ISSUE THREAD

**Issue by sskras** [nero-ui/nero-live#15]
Seems like the Blue Oak 1.0.0 [license URL](https://github.com/nero-ui/nero-live/blob/init/LICENSE.md) in this repo leads to nowhere.  Quoting `README.md`:

`
Distributed under the [Blue Oak Model License](/LICENSE.md)
`

**Comment by kieranpotts** [comment]
Fixed in https://github.com/nero-ui/nero-live/commit/f1130d1eeac867974d5f8de9a7d069b13e366887

Thank you @sskras for letting me know.
